### ISSUE TITLE
Examples > 04.Communication > MultiSerial lacks URL in header comments

### ISSUE THREAD

**Issue by TheOldBrick** [arduino/arduino-examples#31]
Unlike all previous Examples, 04.Communication > MultiSerial does not have a URL in its header comments.  It should contain the URL [https://www.arduino.cc/en/Tutorial/BuiltInExamples/MultiSerialMega](url)

**Comment by per1234** [comment]
Hi @TheOldBrick. Thanks so much for reporting this.

I have now submitted a pull request to add all missing tutorial URLs to the example sketches. Please review and submit your approval if everything is correct.
