### ISSUE TITLE
01.Basics > Blink does not compile for Arduino Nicla Sense ME

### ISSUE THREAD

**Issue by gmacario** [arduino/arduino-examples#47]
Hello,

I followed the documentation published on link "Built-in Examples" of <https://docs.arduino.cc/hardware/nicla-sense-me> and attempted to build example "01.Basics > Blink" for the "Arduino Nicla Sense ME" target board.

However the compilation fails with the following error:

TODO

Any suggestions?

P.S.: My apologies if this is not the proper GitHub repository to report the issue. Please feel free to move elsewhere.
I am quite new with the Nicla and I believe there should be an easy fix, but I could not figure it out myself.

Also, if there is anything I can do to develop a fix I would be more than happy to give it a try and submit a PR.
Just need some guidance. Thanks!

**Comment by per1234** [comment]
Hi @gmacario. Thanks for your report. The Nicla has its own equivalent to the Blink example. The standard Blink example you find in this repository can't be used with that board.

There are instructions for it here:
https://docs.arduino.cc/software/ide-v1/tutorials/getting-started/cores/arduino-mbed_nicla#uploading-a-simple-example

Enjoy using your new Nicla Sense ME!

**Comment by gmacario** [comment]
> Hi @gmacario. Thanks for your report. The Nicla has its own equivalent to the Blink example. The standard Blink example you find in this repository can't be used with that board.

I see... Thank you very much for your hint!
