### ISSUE TITLE
Servo Changeable Frequency Per Pin - For Better Servo Opperation With High End Servos

### ISSUE THREAD

**Issue by Machinelearning3Dprinting** [arduino/arduino-examples#62]
### Describe the request

To have the frequency of a servo pin be adjustable depending on what Hz the Servo needs to operate properly

example code:

```cpp
#include <Servo.h>

Servo myServo;

void setup() {

    myServo.attach(pin, min, max, hz);
//pin = "the number of the pin that the servo is attached to"
//min = "the pulse width, in microseconds, corresponding to the minimum (0 degree) angle on the servo"
//max = "the pulse width, in microseconds, corresponding to the maximum (180 degree) angle on the servo "
//hz = the operation frequency of the servo in hz
```

and have all the calculation done within the library 

### Describe the current behavior

The current and unchangeable frequency of the the library is set to 50Hz which works with the basic servos in the kit's and this is set for all servo not just individuals  

### The examples version

NOT ACTUALLY A PART OF THE "built-in examples" see additional context please

### Additional context

the servo library from "Examples for any board"

I did not see a repository dedicated to "Examples for any board" so as it is pre-installed with the software I saw it fitting to put it under this repository 

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-examples/issues?q=)
- [X] I verified the feature was still missing when using the latest version
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @Machinelearning3Dprinting. Thanks for your suggestion. As you mention, this request is not related to the example sketches hosted in this repository but instead is a request for an enhancement in the Servo library, which is hosted in a separate repository:

https://github.com/arduino-libraries/Servo

I see we have already have a proposal for adding frequency setting support to the library at https://github.com/arduino-libraries/Servo/issues/91.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

>I did not see a repository dedicated to "Examples for any board" so as it is pre-installed with the software I saw it fitting to put it under this repository

Those example sketches are hosted in the individual library repositories. The official Arduino libraries are all listed here:

https://github.com/arduino-libraries
