### ISSUE TITLE
Dimmer.ino does not work

### ISSUE THREAD

**Issue by mhmdaliab** [arduino/arduino-examples#69]
### Describe the problem

Dimmer.ino should change the brightness of a LED to the input value in terminal. But the brightness doesn't change with the value. 

### To reproduce

You can just run it following the instructions in the comment.

### Expected behavior

The brightness of LED is fixed.

### The examples version

main

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-examples/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by per1234** [comment]
See the explanation in the review of the associated pull request: https://github.com/arduino/arduino-examples/pull/70#pullrequestreview-1799560440
